# Generated by Django 5.2 on 2025-05-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTask',
        ),
    ]
