# Generated by Django 5.2 on 2025-05-12 13:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_created_by_alter_project_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmilestone',
            options={'ordering': ['due_date', 'priority']},
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='completion_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='deliverables',
            field=models.TextField(blank=True, help_text='Expected deliverables for this milestone', null=True),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_milestones', to='project.projectmilestone'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='role',
            field=models.CharField(choices=[('manager', 'Project Manager'), ('coordinator', 'Coordinator'), ('member', 'Team Member'), ('advisor', 'Advisor'), ('volunteer', 'Volunteer'), ('monitoring', 'Monitoring/Reporting Officer')], max_length=20),
        ),
    ]
