# Generated by Django 5.2 on 2025-05-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='funds_allocated',
        ),
        migrations.RemoveField(
            model_name='project',
            name='funds_spent',
        ),
        migrations.AddField(
            model_name='project',
            name='full_budget_disbursed',
            field=models.BooleanField(default=False),
        ),
    ]
