# Generated by Django 5.2 on 2025-05-20 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0007_remove_project_funds_allocated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectupdatemedia',
            options={'verbose_name_plural': 'Project Update Media'},
        ),
        migrations.AddField(
            model_name='projectupdatemedia',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectupdatemedia',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectupdatemedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectupdatemedia',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectupdatemedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='projectupdatemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('blueprint', 'Blueprint'), ('contract', 'Contract'), ('diagram', 'Diagram'), ('report', 'Report')], max_length=20),
        ),
        migrations.CreateModel(
            name='MilestoneMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('blueprint', 'Blueprint'), ('contract', 'Contract'), ('diagram', 'Diagram'), ('report', 'Report')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('represents_deliverable', models.BooleanField(default=False, help_text='This media represents a milestone deliverable')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='project.projectmilestone')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Milestone Media',
                'ordering': ['-represents_deliverable', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('blueprint', 'Blueprint'), ('contract', 'Contract'), ('diagram', 'Diagram'), ('report', 'Report')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured media appears prominently in project views')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='project.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project Media',
                'ordering': ['-is_featured', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GenericMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('blueprint', 'Blueprint'), ('contract', 'Contract'), ('diagram', 'Diagram'), ('report', 'Report')], max_length=20)),
                ('file', models.FileField(upload_to='generic_media/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('represents_deliverable', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Media Files',
                'ordering': ['-is_featured', '-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='project_gen_content_dd8873_idx')],
            },
        ),
    ]
