# Generated by Django 5.2.1 on 2025-05-30 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('project', '0008_alter_projectupdatemedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='local_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_projects', to='common.currency'),
        ),
    ]
