# Generated by Django 5.2.1 on 2025-06-03 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_remove_budgetitem_project_expenses'),
        ('project', '0010_projectexpense_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='budget_item',
            field=models.ForeignKey(blank=True, help_text='Budget item this expense is associated with (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expenses', to='finance.budgetitem'),
        ),
    ]
