# Generated by Django 5.2.1 on 2025-06-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_projectexpense_budget_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='local_currency',
            new_name='currency',
        ),
    ]
