# Generated by Django 5.2.1 on 2025-06-03 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('project', '0012_rename_local_currency_project_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_projects', to='common.currency'),
        ),
    ]
