# Generated by Django 5.2 on 2025-05-23 12:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('project', '0008_alter_projectupdatemedia_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('expense_type', models.CharField(choices=[('administrative', 'Administrative'), ('operational', 'Operational'), ('travel', 'Travel'), ('equipment', 'Equipment'), ('supplies', 'Supplies'), ('services', 'Services'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField()),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='org_expense_receipts/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'ordering': ['category', 'subcategory']},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donation_date']},
        ),
        migrations.AlterModelOptions(
            name='donationcampaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='grantreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='inkinddonation',
            options={'ordering': ['-donation_date']},
        ),
        migrations.AlterModelOptions(
            name='recurringdonation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='finance.grant'),
        ),
        migrations.AddField(
            model_name='budget',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='budgeted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='project_expenses',
            field=models.ManyToManyField(blank=True, help_text='Project expenses allocated to this budget item', related_name='budget_items', to='project.projectexpense'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='tax_deductible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grant',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='grant',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grant',
            name='grantor_type',
            field=models.CharField(choices=[('government', 'Government'), ('foundation', 'Foundation'), ('corporate', 'Corporate'), ('individual', 'Individual'), ('other', 'Other')], default='foundation', max_length=20),
        ),
        migrations.AddField(
            model_name='grant',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grantreport',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='grant_reports/'),
        ),
        migrations.AddField(
            model_name='grantreport',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantreport',
            name='report_type',
            field=models.CharField(choices=[('interim', 'Interim Report'), ('final', 'Final Report'), ('financial', 'Financial Report'), ('narrative', 'Narrative Report'), ('annual', 'Annual Report')], default='interim', max_length=20),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='status',
            field=models.CharField(choices=[('pledged', 'Pledged'), ('received', 'Received'), ('declined', 'Declined'), ('expired', 'Expired')], default='pledged', max_length=20),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='payment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='total_donated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(choices=[('project', 'Project'), ('organizational', 'Organizational'), ('department', 'Department'), ('campaign', 'Campaign'), ('grant', 'Grant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='grant',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='inkinddonation',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='inkinddonation',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['budget_type', 'status'], name='finance_bud_budget__85c88c_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['fiscal_year', 'status'], name='finance_bud_fiscal__8128ed_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['budget', 'category'], name='finance_bud_budget__54b0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'donation_date'], name='finance_don_status_f31eab_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', 'status'], name='finance_don_donor_i_b8df7b_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['campaign', 'status'], name='finance_don_campaig_181da6_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcampaign',
            index=models.Index(fields=['is_active', 'start_date'], name='finance_don_is_acti_ea1ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcampaign',
            index=models.Index(fields=['project', 'is_active'], name='finance_don_project_cc35e2_idx'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['status', 'start_date'], name='finance_gra_status_d4c1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['grantor_type', 'status'], name='finance_gra_grantor_fb4906_idx'),
        ),
        migrations.AddIndex(
            model_name='grantreport',
            index=models.Index(fields=['grant', 'status'], name='finance_gra_grant_i_794368_idx'),
        ),
        migrations.AddIndex(
            model_name='grantreport',
            index=models.Index(fields=['due_date', 'status'], name='finance_gra_due_dat_426d49_idx'),
        ),
        migrations.AddIndex(
            model_name='inkinddonation',
            index=models.Index(fields=['status', 'donation_date'], name='finance_ink_status_ad230b_idx'),
        ),
        migrations.AddIndex(
            model_name='inkinddonation',
            index=models.Index(fields=['donor', 'status'], name='finance_ink_donor_i_fb6cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringdonation',
            index=models.Index(fields=['status', 'next_payment_date'], name='finance_rec_status_510c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringdonation',
            index=models.Index(fields=['donor', 'status'], name='finance_rec_donor_i_051e1a_idx'),
        ),
        migrations.AddField(
            model_name='organizationalexpense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_org_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationalexpense',
            name='budget_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizational_expenses', to='finance.budgetitem'),
        ),
        migrations.AddField(
            model_name='organizationalexpense',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_org_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organizationalexpense',
            index=models.Index(fields=['status', 'expense_date'], name='finance_org_status_80ecde_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalexpense',
            index=models.Index(fields=['submitted_by', 'status'], name='finance_org_submitt_6ff747_idx'),
        ),
    ]
