# Generated by Django 5.2 on 2025-05-25 23:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('finance', '0004_accounttransaction_bankaccount_budgetfunding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary account for this campaign')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is currently accepting donations for this campaign')),
                ('priority_order', models.PositiveIntegerField(default=1, help_text='Display order for donation options (1 = highest priority)')),
                ('notes', models.TextField(blank=True, help_text='Special instructions for this account', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign Bank Account',
                'verbose_name_plural': 'Campaign Bank Accounts',
                'ordering': ['priority_order', 'bank_account__name'],
            },
        ),
        migrations.RemoveField(
            model_name='inkinddonation',
            name='image',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='accepts_donations',
            field=models.BooleanField(default=True, help_text='Whether this account can receive donations'),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Upload receipt or proof of donation', null=True, upload_to='donation_receipts/'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='available_from',
            field=models.DateField(blank=True, help_text='Date when funds become available', null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='available_until',
            field=models.DateField(blank=True, help_text='Date when funds expire if not used', null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_funding_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='restrictions',
            field=models.TextField(blank=True, help_text='Any restrictions on how these funds can be used', null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Upload receipt or photo of in-kind donation', null=True, upload_to='in_kind_donation_receipts/'),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Upload receipt or proof of recurring donation setup', null=True, upload_to='recurring_donation_receipts/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used if currency conversion was needed', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='funding_type',
            field=models.CharField(choices=[('donation', 'General Donation'), ('campaign', 'Campaign'), ('grant', 'Grant'), ('internal', 'Internal Funds'), ('partnership', 'Partnership Funding'), ('government', 'Government Funding'), ('investment', 'Investment Returns'), ('fundraising_event', 'Fundraising Event'), ('corporate_sponsorship', 'Corporate Sponsorship'), ('foundation_grant', 'Foundation Grant'), ('crowdfunding', 'Crowdfunding'), ('other', 'Other')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['accepts_donations', 'is_active'], name='finance_ban_accepts_c9b49b_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingsource',
            index=models.Index(fields=['available_from', 'available_until'], name='finance_fun_availab_bf7aa8_idx'),
        ),
        migrations.AddField(
            model_name='campaignbankaccount',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_campaign_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignbankaccount',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_bank_accounts', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='campaignbankaccount',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_bank_accounts', to='finance.donationcampaign'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='bank_accounts',
            field=models.ManyToManyField(blank=True, help_text='Bank accounts that can receive donations for this campaign', related_name='campaigns', through='finance.CampaignBankAccount', to='finance.bankaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignbankaccount',
            unique_together={('campaign', 'bank_account')},
        ),
    ]
