# Generated by Django 5.2 on 2025-05-26 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('finance', '0005_campaignbankaccount_remove_inkinddonation_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed'), ('pending', 'Pending Activation'), ('suspended', 'Suspended')], default='active', help_text='Current status of the account', max_length=20),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='auto_reconciliation_enabled',
            field=models.BooleanField(default=False, help_text='Whether automatic reconciliation is enabled'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch_address',
            field=models.TextField(blank=True, help_text='Physical address of the bank branch', null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='compliance_status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('pending_review', 'Pending Review'), ('non_compliant', 'Non-Compliant'), ('under_investigation', 'Under Investigation')], default='compliant', help_text='Compliance status with banking regulations', max_length=20),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='debit_card_enabled',
            field=models.BooleanField(default=False, help_text='Whether a debit card is available for this account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, help_text='International Bank Account Number', max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Annual interest rate (as decimal, e.g., 0.0250 for 2.5%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_reconciled_date',
            field=models.DateTimeField(blank=True, help_text='Date when account was last reconciled', null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_transaction_date',
            field=models.DateTimeField(blank=True, help_text='Date of the most recent transaction', null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='mobile_banking_enabled',
            field=models.BooleanField(default=False, help_text='Whether mobile banking is enabled for this account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='monthly_maintenance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly maintenance fee charged by the bank', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this account', null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='online_banking_enabled',
            field=models.BooleanField(default=False, help_text='Whether online banking is enabled for this account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='overdraft_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum overdraft amount allowed', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='overdraft_protection',
            field=models.BooleanField(default=False, help_text='Whether overdraft protection is enabled'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', help_text='Risk assessment level for this account', max_length=10),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='routing_number',
            field=models.CharField(blank=True, help_text='Bank routing number (for US accounts)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='swift_code',
            field=models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=11, null=True),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_status'], name='finance_ban_account_0a93ba_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['compliance_status'], name='finance_ban_complia_bd134e_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['risk_level'], name='finance_ban_risk_le_d8ad04_idx'),
        ),
    ]
