# Generated by Django 5.2 on 2025-05-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_budgetitem_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='spent_amount',
        ),
    ]
