# Generated by Django 5.2 on 2025-05-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_budgetitem_spent_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttransaction',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='spent_amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='fundingsource',
            name='amount_allocated',
        ),
    ]
