# Generated by Django 5.2 on 2025-05-29 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_accounttransaction_net_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetfunding',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_funding', to='finance.fundingsource'),
        ),
    ]
