# Generated by Django 5.2 on 2025-05-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_budgetfunding_funding_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetfunding',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.fundingsource'),
        ),
    ]
