# Generated by Django 5.2 on 2025-05-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_fundallocation_allocated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalexpense',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
