# Generated by Django 5.2 on 2025-06-01 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('finance', '0015_alter_organizationalexpense_title'),
        ('project', '0009_project_local_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inkinddonation',
            options={'ordering': ['-pledge_date'], 'verbose_name': 'In-Kind Donation', 'verbose_name_plural': 'In-Kind Donations'},
        ),
        migrations.RemoveIndex(
            model_name='donationcampaign',
            name='finance_don_is_acti_ea1ce0_idx',
        ),
        migrations.RemoveIndex(
            model_name='donationcampaign',
            name='finance_don_project_cc35e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='inkinddonation',
            name='finance_ink_status_ad230b_idx',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='deposit_date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='deposited_to_account',
        ),
        migrations.RemoveField(
            model_name='donationcampaign',
            name='bank_accounts',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='total_donated',
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_source',
            field=models.CharField(choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('event', 'Fundraising Event'), ('mail', 'Direct Mail'), ('phone', 'Phone Campaign'), ('social_media', 'Social Media'), ('peer_to_peer', 'Peer-to-Peer'), ('corporate', 'Corporate Partnership'), ('grant', 'Grant/Foundation'), ('other', 'Other')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_recurring_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='referral_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='allow_anonymous_donations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='allow_in_kind_donations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='allow_recurring_donations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('general', 'General Fundraising'), ('emergency', 'Emergency Response'), ('project_specific', 'Project Specific'), ('capacity_building', 'Capacity Building'), ('equipment', 'Equipment Purchase'), ('scholarship', 'Scholarship Fund'), ('research', 'Research Initiative'), ('community_outreach', 'Community Outreach')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='launch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='managed_by',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage this campaign', related_name='managed_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='minimum_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount needed for campaign success', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='campaign_videos/'),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual value assessed upon receipt', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='brand_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='condition_on_receipt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='documentation',
            field=models.FileField(blank=True, help_text='Additional documentation (certificates, warranties, etc.)', null=True, upload_to='in_kind_donation_docs/'),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='donor_organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current market value if different from estimated', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='photos',
            field=models.FileField(blank=True, help_text='Photos of the donated items', null=True, upload_to='in_kind_donation_photos/'),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='pickup_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='pledge_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='receipt_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='special_handling_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='storage_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='tax_deductible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='valuation_method',
            field=models.CharField(blank=True, help_text='How the value was determined', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='failed_payment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='max_failed_payments',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='payment_processor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.ForeignKey(help_text='Currency of the donation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='common.currency'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash'), ('check', 'Check'), ('mobile_money', 'Mobile Money'), ('cryptocurrency', 'Cryptocurrency'), ('wire_transfer', 'Wire Transfer'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='campaign_images/'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='target_currency',
            field=models.ForeignKey(help_text='Currency for the target amount', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='common.currency'),
        ),
        migrations.AlterField(
            model_name='inkinddonation',
            name='category',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('supplies', 'Supplies'), ('services', 'Professional Services'), ('food', 'Food & Beverages'), ('clothing', 'Clothing'), ('books', 'Books & Educational Materials'), ('technology', 'Technology'), ('vehicles', 'Vehicles'), ('real_estate', 'Real Estate'), ('artwork', 'Artwork'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='inkinddonation',
            name='donation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inkinddonation',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_in_kind_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inkinddonation',
            name='status',
            field=models.CharField(choices=[('pledged', 'Pledged'), ('confirmed', 'Confirmed'), ('received', 'Received'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pledged', max_length=20),
        ),
        migrations.AlterField(
            model_name='inkinddonation',
            name='valuation_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_kind_donations', to='common.currency'),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_donations', to='common.currency'),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Bi-annually'), ('annually', 'Annually')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_method', 'status'], name='finance_don_payment_4288a7_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_source', 'donation_date'], name='finance_don_donatio_0411d1_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcampaign',
            index=models.Index(fields=['status', 'start_date'], name='finance_don_status_5980cf_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcampaign',
            index=models.Index(fields=['campaign_type', 'status'], name='finance_don_campaig_f54864_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcampaign',
            index=models.Index(fields=['is_featured', 'status'], name='finance_don_is_feat_60e652_idx'),
        ),
        migrations.AddIndex(
            model_name='inkinddonation',
            index=models.Index(fields=['status', 'pledge_date'], name='finance_ink_status_e85fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='inkinddonation',
            index=models.Index(fields=['category', 'status'], name='finance_ink_categor_213adf_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringdonation',
            index=models.Index(fields=['frequency', 'status'], name='finance_rec_frequen_f53e7e_idx'),
        ),
    ]
