# Generated by Django 5.2 on 2025-06-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_inkinddonation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('general', 'General Fundraising'), ('emergency', 'Emergency Response'), ('project_specific', 'Project Specific'), ('capacity_building', 'Capacity Building'), ('equipment', 'Equipment Purchase'), ('scholarship', 'Scholarship Fund'), ('research', 'Research Initiative'), ('community_outreach', 'Community Outreach')], default='general', max_length=100),
        ),
    ]
