# Generated by Django 5.2 on 2025-06-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_donationcampaign_campaign_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
