# Generated by Django 5.2 on 2025-06-01 12:51

import django.db.models.deletion
import mainapps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('finance', '0018_alter_donationcampaign_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='target_currency',
            field=models.ForeignKey(default=mainapps.finance.models.DonationCampaign.get_default_currency, help_text='Currency for the target amount', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='common.currency'),
        ),
    ]
