# Generated by Django 5.2 on 2025-06-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_donationcampaign_target_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash'), ('check', 'Check'), ('mobile_money', 'Mobile Money'), ('cryptocurrency', 'Cryptocurrency'), ('wire_transfer', 'Wire Transfer'), ('other', 'Other')], default='credit_card', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash'), ('check', 'Check'), ('mobile_money', 'Mobile Money'), ('cryptocurrency', 'Cryptocurrency'), ('wire_transfer', 'Wire Transfer'), ('other', 'Other')], default='credit_card', max_length=100),
        ),
    ]
