# Generated by Django 5.2.1 on 2025-06-02 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_alter_donation_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringdonation',
            name='failed_payment_count',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='payment_count',
        ),
        migrations.AddField(
            model_name='donation',
            name='recurring_donation',
            field=models.ForeignKey(blank=True, help_text='Linked recurring donation if this is a recurring payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_instances', to='finance.recurringdonation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='recurring_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Sequence number for recurring payments (1st, 2nd, etc.)'),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive failed payments'),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed'), ('completed', 'Completed')], default='inactive', max_length=20),
        ),
    ]
