# Generated by Django 5.2.1 on 2025-06-03 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_remove_recurringdonation_failed_payment_count_and_more'),
        ('project', '0009_project_local_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalexpense',
            name='project_instance',
            field=models.OneToOneField(blank=True, help_text='Link to a project expense if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizational_expenses', to='project.projectexpense'),
        ),
    ]
