# Generated by Django 5.2.1 on 2025-06-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_organizationalexpense_project_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='project_expenses',
        ),
    ]
