# Generated by Django 5.2.1 on 2025-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_remove_budgetitem_project_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='title',
            field=models.CharField(help_text='Title of the budget item', max_length=255, null=True),
        ),
    ]
