# Generated by Django 5.2.1 on 2025-06-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_budgetitem_title'),
        ('project', '0011_projectexpense_budget_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalexpense',
            name='project_instance',
            field=models.OneToOneField(blank=True, help_text='Link to a project expense if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizational_expense', to='project.projectexpense'),
        ),
    ]
