# Generated by Django 5.2 on 2025-05-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_user_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expertise',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='accounts.expertise'),
        ),
    ]
