# Generated by Django 5.2 on 2025-05-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_expertise_userprofile_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expertise',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expertise',
            field=models.ManyToManyField(blank=True, null=True, related_name='expertise', to='accounts.expertise'),
        ),
    ]
