# Generated by Django 5.2 on 2025-05-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_expertise_userprofile_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='expertise', to='accounts.expertise'),
        ),
    ]
