# Generated by Django 5.2 on 2025-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userprofile_profile_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_link',
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
