# Generated by Django 5.2 on 2025-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_userprofile_linkedin_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_DB_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_DB_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_DB_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_standard_member',
            field=models.BooleanField(default=False),
        ),
    ]
