# Generated by Django 5.2 on 2025-05-08 14:56

import mainapps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_is_db_admin_userprofile_is_db_executive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapps.accounts.models.profile_image_path),
        ),
    ]
