# Generated by Django 5.2 on 2025-05-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userprofile_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=4)),
                ('country_code', models.CharField(max_length=2)),
                ('region_code', models.CharField(max_length=3)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reference Counter',
                'verbose_name_plural': 'Reference Counters',
                'unique_together': {('role_code', 'country_code', 'region_code')},
            },
        ),
    ]
