# Generated by Django 5.2 on 2025-05-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0002_activitylog_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='changes',
        ),
    ]
